name: pyart-xarray-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - pys2index
  - gdal
  - numpy
  - scipy
  - matplotlib
  - pandas
  - netcdf4
  - arm_pyart
  - pytest
  - trmm_rsl
  - wradlib
  - cartopy
  - cvxopt
  - xarray
  - sphinx
  - ipython
  - pandoc
  - netcdf4
  - pytest
  - pkg-config
  - xcollection
  - xoak
  - jupyterlab
  - pip
  - pip:
      - sphinx_gallery
      - sphinx-copybutton
      - nbsphinx
      - pooch
