
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: python-${{ matrix.python-version }}
    if: github.repository == 'mgrover1/pyart-xarray-sandbox'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        id: conda
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: pyart-xarray-dev
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          mamba-version: '*'
          use-mamba: true
          miniforge-variant: Mambaforge
          environment-file: ci/environment.yml

      - name: Set TRMM RSL path
        env:
          RSL_PATH: ${{env.CONDA_PKGS_DIR}}/trmm_rsl-1.49-3 
        run: echo "$RSL_PATH"